[package]
name = "luminal_nn"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
luminal = { path = "../.." }
rustc-hash = "2.1.1"
rand = "0.9.2"

[dev-dependencies]
luminal_reference = { path = "../luminal_reference" }
scalar_refs = { path = "../../tests/scalar_refs" }
dfdx = { version = "0.13", features = ["f16"] }
paste = "1.0.14"
candle-core = "0.9.2-alpha.1"
