//! Translation test for real complex-valued `torch.export.save` fixtures.
//!
//! The fixture is generated by exporting a module that adds, multiplies,
//! divides, and takes components / magnitudes / elementary functions of
//! `complex64` tensors. It lives in `<workspace>/target/luminal_fixtures`
//! and the test skips when it is absent, so `cargo test` stays runnable
//! without a torch environment.

use luminal::prelude::DType;
use luminal_pytorch_utils::{Translation, parse_pt2, translate};

fn fixture(name: &str) -> Option<Translation> {
    let path = format!(
        "{}/../../../target/luminal_fixtures/{name}.pt2",
        env!("CARGO_MANIFEST_DIR")
    );
    if !std::path::Path::new(&path).exists() {
        eprintln!("skipping: {path} not found");
        return None;
    }
    let parsed = parse_pt2(&path).expect("parse pt2");
    Some(translate(&parsed).unwrap_or_else(|e| panic!("translate {name}: {e:#}")))
}

#[test]
fn complex_ops_translate() {
    let Some(t) = fixture("b11_complex") else {
        return;
    };
    // add, mul, div, view_as_real, view_as_complex, real, imag, abs, exp,
    // sqrt, sigmoid.
    assert_eq!(t.outputs.len(), 11, "complex fixture outputs");
    // Both graph inputs are complex64: interleaved [2, 3, 2] backing storage
    // with an F32 component dtype.
    assert_eq!(t.inputs.len(), 2);
    for input in &t.inputs {
        assert_eq!(input.dtype, DType::F32, "{}", input.graph_name);
        assert_eq!(input.shape, vec![2, 3, 2], "{}", input.graph_name);
    }
    // Every output is real-valued (complex outputs are carried as components
    // and repacked only at the boundary). `view_as_real` is the one output
    // that keeps the trailing component axis; the rest expose their logical
    // [2, 3] shape.
    for output in &t.outputs {
        assert_eq!(output.dtype, DType::F32, "{}", output.graph_name);
        if output.graph_name == "view_as_real" {
            assert_eq!(output.shape, vec![2, 3, 2], "{}", output.graph_name);
        } else {
            assert_eq!(output.shape, vec![2, 3], "{}", output.graph_name);
        }
    }
}
