//! Translation smoke tests against a real `torch.export.save` fixture.
//!
//! The fixture is generated by the Python side (see
//! `luminal_reference/tests/test_mlp.py`); the test skips when absent so
//! `cargo test` stays runnable without a torch environment.

use luminal::prelude::{DType, IntExpr};
use luminal_pytorch_utils::{InputKind, parse_pt2, translate};

const MLP_PT2: &str = "/tmp/luminal_mlp.pt2";

/// A translated boundary shape is symbolic; this fixture is static, so every
/// dim must resolve to a literal.
fn concrete(shape: &[IntExpr]) -> Vec<usize> {
    shape
        .iter()
        .map(|dim| dim.to_usize().expect("static fixture dim"))
        .collect()
}

#[test]
fn mlp_translates_to_the_recorder_frontend() {
    if !std::path::Path::new(MLP_PT2).exists() {
        eprintln!("skipping: {MLP_PT2} not found");
        return;
    }
    let parsed = parse_pt2(MLP_PT2).expect("parse pt2");
    let translation = translate(&parsed).expect("translate mlp");

    assert_eq!(translation.inputs.len(), 5);
    let params: Vec<_> = translation
        .inputs
        .iter()
        .filter(|input| matches!(input.kind, InputKind::Parameter { .. }))
        .collect();
    assert_eq!(params.len(), 4, "two weights + two biases");
    assert_eq!(
        params
            .iter()
            .map(|input| input.parameter_name.clone().unwrap())
            .collect::<Vec<_>>(),
        vec!["fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias"]
    );
    let user: Vec<_> = translation
        .inputs
        .iter()
        .filter(|input| matches!(input.kind, InputKind::UserInput { .. }))
        .collect();
    assert_eq!(user.len(), 1);
    assert_eq!(concrete(&user[0].shape), vec![3, 4]);

    assert_eq!(translation.outputs.len(), 1);
    assert_eq!(concrete(&translation.outputs[0].shape), vec![3, 2]);
    assert_eq!(translation.outputs[0].dtype, DType::F32);
    assert!(translation.outputs[0].mutation_target.is_none());
}
