[package]
name = "luminal_metal"
version = "0.2.0"
edition.workspace = true
description = "Metal backend for luminal"
license = "MIT OR Apache-2.0"

[dependencies]
luminal = { path = "../.." }
anyhow = "1"
rustc-hash = "2"
petgraph = "0.6.4"
rand = "0.9.2"
colored = "2.0.4"
half = "2.7.1"

[target.'cfg(target_os = "macos")'.dependencies]
metal = { version = "0.31", features = ["mps"] }
objc = "0.2"

[dev-dependencies]
model_zoo = { path = "../model_zoo" }
luminal_reference = { path = "../luminal_reference" }
luminal_nn = { path = "../luminal_nn" }
safetensors = "0.7"
hf-hub = { version = "0.4", default-features = false, features = ["rustls-tls", "ureq"] }
tokenizers = "0.22.2"
luminal_tracing = { path = "../luminal_tracing" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
