[package]
name = "luminal_pytorch_utils"
version = "0.1.0"
edition.workspace = true

[dependencies]
luminal = { path = "../../.." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "2"
anyhow = "1"
tracing = "0.1"
rustc-hash = "2.1.1"

[dev-dependencies]
luminal_reference = { path = "../../luminal_reference" }

