name: Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    core_unit_test:
        name: Core Unit Tests
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/luminal-ai/luminal-docker:cpu
        timeout-minutes: 20

        steps:
            - uses: actions/checkout@v6
            - name: Run tests
              run: cargo test --workspace --exclude luminal_cuda --exclude luminal_metal --exclude luminal_bench --verbose
    metal_unit_test:
        name: Metal Unit Tests
        runs-on: macos-14
        timeout-minutes: 30

        steps:
            - uses: actions/checkout@v6
            - name: Run Metal crate tests
              run: rustup update; cargo test -p luminal_metal --verbose -- --test-threads=1
